### ISSUE TITLE
Problems compiling SASS

### ISSUE THREAD

**Issue by jota-v** [mercadolibre/generator-chico-theme#5]
Fix updating module "gulp-sass" to version 2.0.3 (current version 1.3.3).

![screen shot 2015-10-22 at 4 01 29 pm](https://cloud.githubusercontent.com/assets/437205/10675413/66bbcc44-78d6-11e5-8faa-f53e9b7a911b.png)

**Comment by atma** [comment]
It is occurs with every package that should be compiled from source after the node version change with `nvm` or node version upgrade. In you case during the `node-sass` upgrade to version 2.0.3 sass binaries was compiled again. So `npm rebuild node-sass` should resolve the issue too.

**Comment by jota-v** [comment]
Understood. Good to know!
Thanks Oleh
